<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>ScreenFXBuddy</PackageId>
    <Version>5.0.0</Version>
    <Title>ScreenFXBuddy</Title>
    <Authors>dmanning23</Authors>
    <description>Post-processing screen effects built for fighting games</description>
    <PackageProjectUrl>https://github.com/dmanning23/CameraBuddy</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/dmanning23/ScreenFXBuddy</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>monogame</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="GameTimer" Version="5.*" />
  </ItemGroup>
</Project>